/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Users {
  id: number;
}

export interface Words {
  correct: Generated<number>;
  incorrect: Generated<number>;
  original: string;
  translate: string;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
  wordId: Generated<number>;
}

export interface DB {
  users: Users;
  words: Words;
}
